dist: xenial
language: python

python:
  - "pypy2.7-6.0.0"
  # - "pypy2.7-7.0.0"

install:
  - travis_retry wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-src.tar.bz2
  - tar -xjf pypy2.7-v7.0.0-src.tar.bz2
  - mv pypy2.7-v7.0.0-src pypy
# command to run tests
script:
  - PYTHONPATH=$PYTHONPATH:pypy nosetests
  - PYTHONPATH=$PYTHONPATH:pypy ./som.sh -cp Smalltalk TestSuite/TestHarness.som
  - PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch src/targetsomstandalone.py
  - ./RTruffleSOM-no-jit -cp Smalltalk TestSuite/TestHarness.som
  #- PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch -Ojit src/targetsomstandalone.py
  #- ./RTruffleSOM-jit -cp Smalltalk TestSuite/TestHarness.som
